default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: tweet_development

test:
  <<: *default
  database: meclub3_test

production:
  adapter: postgresql
  database: tweet_production
  username: postgres
  password: cell_evaluation      
  host: localhost  
  port: 5432
  pool: 10
  timeout: 5000
